### PR TITLE
create xsd transform

### PR DESCRIPTION
**Pull request by wandmagic**
# Committer Notes

{Please provide a brief description of what this PR accomplishes. Be sure to reference any issues addressed. If the PR is a work-in-progress submitted for early review, please include [WIP] at the beginning of the title or mark the PR as DRAFT.}

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/OSCAL/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

(For reviewers: [The wiki has guidance](https://github.com/usnistgov/OSCAL/wiki/Issue-Review) on code review and overall issue review for completeness.)

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

### CODE REVIEW

**Comment by iMichaela** [comment]
@wandmagic - the branch [prototype-shared-responsibility-model-rebased](https://github.com/iMichaela/OSCAL/tree/prototype-shared-responsibility-model-rebased) is the old prototype SR model created by Chris and rebased against `develop`. I am assuming you want to submit the PR against the branch `prototype-shared-responsibility-model-rebased-rc1-prep-updates` so the contribution goes into the PR #2000

**Comment by wandmagic** [comment]
I've changed the base for this PR

**Review by iMichaela — CHANGES_REQUESTED** [review]
CHANGE REQUESTED:
The transformation is from OSCAL 1..1.2 to OSCAL 1.2.0 (not 1.2.1), and the name should indicate it only converts the ssp. 
NICE TO HAVE:
A test using the oscal-content 1.3.0 release example (ssp-leveraged and ssp-leveraging) will be needed.
REMIDER:
The component-definition model will also need the `responsibility` included .

**Comment by iMichaela** [comment]
> CHANGE REQUESTED: The transformation is from OSCAL 1..1.2 to OSCAL 1.2.0 (not 1.2.1), and the name should indicate it only converts the ssp. NICE TO HAVE: A test using the oscal-content 1.3.0 release example (ssp-leveraged and ssp-leveraging) will be needed. REMIDER: The component-definition model will also need the `responsibility` included .

@wandmagic  - please note the  request  above  ^

**Review by iMichaela — COMMENTED** [review]
This PR is not transforming the OSCAL SSPs from OSCAL v1.1.2 to v 1.2.0, it is changing XSD schemas.

**Comment by iMichaela** [comment]
Closing it for now since it is not what is needed. We can re-open it if it becomes handy for any reasons later.

**Pull request closed without merging**
